apiVersion: v1
entries:
  app-mobility:
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2022-11-07T01:51:56.713411765-05:00"
    dependencies:
    - condition: cert-manager.enabled
      name: cert-manager
      repository: https://charts.jetstack.io
      version: 1.8.2
    - condition: velero.enabled
      name: velero
      repository: https://vmware-tanzu.github.io/helm-charts
      version: 2.29.8
    description: A Helm chart deploying Application Mobility
    digest: f43dc501252815b3eb1b609fc8b748f24bbb7165a98b1ebfac1728daa16d185d
    name: app-mobility
    type: application
    urls:
    - app-mobility-0.1.0.tgz
    version: 0.1.0
generated: "2022-11-07T01:51:56.702015823-05:00"
